/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GalleryImage = IDL.Record({
  'blob' : ExternalBlob,
  'caption' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const LetterBox = IDL.Text;
export const SiteContent = IDL.Record({
  'siteTitle' : IDL.Text,
  'tagline' : IDL.Text,
  'aboutTitle' : IDL.Text,
  'heroSubtitle' : IDL.Text,
  'heroImage' : IDL.Opt(ExternalBlob),
  'aboutBody' : IDL.Text,
  'contactEmail' : IDL.Text,
  'contactAddress' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const SocialMedia = IDL.Record({
  'url' : IDL.Text,
  'platform' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGalleryImage' : IDL.Func([ExternalBlob, IDL.Opt(IDL.Text)], [], []),
  'addGalleryImages' : IDL.Func([IDL.Vec(GalleryImage)], [], []),
  'addSocialMedia' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getHeroImage' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getLetterBox' : IDL.Func([IDL.Nat], [LetterBox], ['query']),
  'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
  'getSocialMediaLinks' : IDL.Func([], [IDL.Vec(SocialMedia)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeGalleryImage' : IDL.Func([IDL.Nat], [], []),
  'removeSocialMedia' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setHeroImage' : IDL.Func([ExternalBlob], [], []),
  'setLetterBox' : IDL.Func([IDL.Nat, LetterBox], [], []),
  'setSiteContent' : IDL.Func([SiteContent], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GalleryImage = IDL.Record({
    'blob' : ExternalBlob,
    'caption' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const LetterBox = IDL.Text;
  const SiteContent = IDL.Record({
    'siteTitle' : IDL.Text,
    'tagline' : IDL.Text,
    'aboutTitle' : IDL.Text,
    'heroSubtitle' : IDL.Text,
    'heroImage' : IDL.Opt(ExternalBlob),
    'aboutBody' : IDL.Text,
    'contactEmail' : IDL.Text,
    'contactAddress' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const SocialMedia = IDL.Record({ 'url' : IDL.Text, 'platform' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGalleryImage' : IDL.Func([ExternalBlob, IDL.Opt(IDL.Text)], [], []),
    'addGalleryImages' : IDL.Func([IDL.Vec(GalleryImage)], [], []),
    'addSocialMedia' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getHeroImage' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getLetterBox' : IDL.Func([IDL.Nat], [LetterBox], ['query']),
    'getSiteContent' : IDL.Func([], [SiteContent], ['query']),
    'getSocialMediaLinks' : IDL.Func([], [IDL.Vec(SocialMedia)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeGalleryImage' : IDL.Func([IDL.Nat], [], []),
    'removeSocialMedia' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setHeroImage' : IDL.Func([ExternalBlob], [], []),
    'setLetterBox' : IDL.Func([IDL.Nat, LetterBox], [], []),
    'setSiteContent' : IDL.Func([SiteContent], [], []),
  });
};

export const init = ({ IDL }) => { return []; };