/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface GalleryImage {
  'blob' : ExternalBlob,
  'caption' : [] | [string],
}
export type LetterBox = string;
export interface SiteContent {
  'siteTitle' : string,
  'tagline' : string,
  'aboutTitle' : string,
  'heroSubtitle' : string,
  'heroImage' : [] | [ExternalBlob],
  'aboutBody' : string,
  'contactEmail' : string,
  'contactAddress' : string,
  'contactPhone' : string,
}
export interface SocialMedia { 'url' : string, 'platform' : string }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGalleryImage' : ActorMethod<[ExternalBlob, [] | [string]], undefined>,
  'addGalleryImages' : ActorMethod<[Array<GalleryImage>], undefined>,
  'addSocialMedia' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getHeroImage' : ActorMethod<[], [] | [ExternalBlob]>,
  'getLetterBox' : ActorMethod<[bigint], LetterBox>,
  'getSiteContent' : ActorMethod<[], SiteContent>,
  'getSocialMediaLinks' : ActorMethod<[], Array<SocialMedia>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeGalleryImage' : ActorMethod<[bigint], undefined>,
  'removeSocialMedia' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setHeroImage' : ActorMethod<[ExternalBlob], undefined>,
  'setLetterBox' : ActorMethod<[bigint, LetterBox], undefined>,
  'setSiteContent' : ActorMethod<[SiteContent], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];